ndarray 생성 관련 함수

In [1]:
import numpy as np
np.zeros(10) # 실수형으로 나옴

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [7]:
np.full(6,3)

array([3, 3, 3, 3, 3, 3])

In [8]:
np.full((2,3),np.nan)

array([[nan, nan, nan],
       [nan, nan, nan]])

함수 arange

In [9]:
range(10)

range(0, 10)

In [10]:
type(range(10))

range

In [12]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
type(np.arange(10))

numpy.ndarray

In [17]:
np.arange(1.,3)

array([1., 2.])

In [18]:
np.arange(1.,3).dtype

dtype('float64')

reshape

In [20]:
a=np.arange(1,100,2)
a.reshape(10,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [21]:
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [22]:
a.shape=(10,5)
a

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

ndarray의 연산원리

In [24]:
a=np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
a+a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [27]:
a*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [28]:
a+[1,2,3]

array([[2, 4, 6],
       [5, 7, 9]])

연습문제 1: 네모 칸의 코드?

In [29]:
a=np.arange(1.5,12,2);a

array([ 1.5,  3.5,  5.5,  7.5,  9.5, 11.5])

In [32]:
b=a.reshape(2,3).astype("str")
b

array([['1.5', '3.5', '5.5'],
       ['7.5', '9.5', '11.5']], dtype='<U32')

In [34]:
c=(2*a).reshape(3,2).astype("int")
c

array([[ 3,  7],
       [11, 15],
       [19, 23]])

연습문제 2: 네모 칸의 코드 ?

In [35]:
np.full(100,'apple')

array(['apple', 'apple', 'apple', 'apple', 'apple', 'apple', 'apple',
       'apple', 'apple', 'apple', 'apple', 'apple', 'apple', 'apple',
       'apple', 'apple', 'apple', 'apple', 'apple', 'apple', 'apple',
       'apple', 'apple', 'apple', 'apple', 'apple', 'apple', 'apple',
       'apple', 'apple', 'apple', 'apple', 'apple', 'apple', 'apple',
       'apple', 'apple', 'apple', 'apple', 'apple', 'apple', 'apple',
       'apple', 'apple', 'apple', 'apple', 'apple', 'apple', 'apple',
       'apple', 'apple', 'apple', 'apple', 'apple', 'apple', 'apple',
       'apple', 'apple', 'apple', 'apple', 'apple', 'apple', 'apple',
       'apple', 'apple', 'apple', 'apple', 'apple', 'apple', 'apple',
       'apple', 'apple', 'apple', 'apple', 'apple', 'apple', 'apple',
       'apple', 'apple', 'apple', 'apple', 'apple', 'apple', 'apple',
       'apple', 'apple', 'apple', 'apple', 'apple', 'apple', 'apple',
       'apple', 'apple', 'apple', 'apple', 'apple', 'apple', 'apple',
       'apple', 'app

인덱싱과 슬라이싱 : 1차원

In [36]:
a=np.arange(1,7);a

array([1, 2, 3, 4, 5, 6])

In [37]:
a[5] #인덱싱은 1차원 내림 

6

In [38]:
a[2:4]

array([3, 4])

In [41]:
a[5]=12;a

array([ 1,  2,  3,  4,  5, 12])

In [43]:
a[1:3]=[14,13];a #슬라이싱은 차원 유지해줌

array([ 1, 14, 13,  4,  5, 12])

In [45]:
a[1:3]=12;a

array([ 1, 12, 12,  4,  5, 12])

In [46]:
a[1:3]=[14];a

array([ 1, 14, 14,  4,  5, 12])

Step : 1차원

In [47]:
a=np.arange(1,10,2);a

array([1, 3, 5, 7, 9])

In [48]:
a[::]

array([1, 3, 5, 7, 9])

In [49]:
a[::2]

array([1, 5, 9])

In [50]:
a[2::2]

array([5, 9])

In [51]:
a[::-1]

array([9, 7, 5, 3, 1])

In [52]:
a[::-2]

array([9, 5, 1])

In [53]:
a[-2::-1]

array([7, 5, 3, 1])

In [54]:
a[2::-1]

array([5, 3, 1])

인덱싱과 슬라이싱 : 2차원

In [55]:
a=np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
a[-1]

array([ 9, 10, 11, 12])

In [57]:
a[0][-1]

4

In [58]:
a[-1][0]

9

In [59]:
a[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [60]:
a[0:1]

array([[1, 2, 3, 4]])

In [61]:
a[0:2][0]

array([1, 2, 3, 4])

In [62]:
a[0:2][0][1:]

array([2, 3, 4])

Step : 2차원

In [64]:
a=np.arange(1,13).reshape(3,4);a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [65]:
a[::2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [66]:
a[::-1]

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [67]:
a[1::-1]

array([[5, 6, 7, 8],
       [1, 2, 3, 4]])

In [68]:
a[::2][1]

array([ 9, 10, 11, 12])

In [69]:
a[::2][1:2]

array([[ 9, 10, 11, 12]])

In [70]:
a[::2][::2]

array([[1, 2, 3, 4]])

행과 열 : 인덱싱, 슬라이싱

In [73]:
a=np.arange(1,13).reshape(3,4);a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [74]:
a[0][1]

2

In [75]:
a[0,1]

2

In [76]:
a[0:2][1]

array([5, 6, 7, 8])

In [78]:
a[0:2,1] # 슬라이싱이 있으면 차원 유지 인덱싱은 차원 감소 

array([2, 6])

In [79]:
a[:][:-1]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [80]:
a[:,:-1]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [81]:
a[0,]

array([1, 2, 3, 4])

연습문제 3: 네모칸 코드?

In [83]:
a=np.arange(1,13).reshape(3,4);a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [84]:
a[0:2,1:4]

array([[2, 3, 4],
       [6, 7, 8]])

In [85]:
a[2]

array([ 9, 10, 11, 12])

In [86]:
a[2:3]

array([[ 9, 10, 11, 12]])

In [88]:
a[0:3,0:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [89]:
a[0:3,0:2][1]

array([5, 6])

In [90]:
a[0:3,0:2][1:2]

array([[5, 6]])