2차원 ndarray : 값 변경

In [1]:
import numpy as np
b=np.arange(1,9).reshape(2,4);b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [2]:
b[0]=4;b

array([[4, 4, 4, 4],
       [5, 6, 7, 8]])

In [3]:
b[0]=100;b

array([[100, 100, 100, 100],
       [  5,   6,   7,   8]])

In [4]:
b[0]=[1,2,3,4];b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
b[0]=range(2,6);b

array([[2, 3, 4, 5],
       [5, 6, 7, 8]])

In [10]:
b[0]=np.arange(12,16);b

array([[12, 13, 14, 15],
       [ 5,  6,  7,  8]])

In [11]:
b[0:1]=4;b

array([[4, 4, 4, 4],
       [5, 6, 7, 8]])

In [12]:
b[0:1]=5;b

array([[5, 5, 5, 5],
       [5, 6, 7, 8]])

In [13]:
b[0:1]=[1,2,3,4];b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
b[0:2]=np.arange(12,16);b

array([[12, 13, 14, 15],
       [12, 13, 14, 15]])

In [15]:
b[0:2]=[[12,13,14,15],[16,17,18,19]];b

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

In [17]:
b[0:2]=np.arange(102,110).reshape(2,4);b

array([[102, 103, 104, 105],
       [106, 107, 108, 109]])

In [18]:
b[0:2,0:2]=4;b

array([[  4,   4, 104, 105],
       [  4,   4, 108, 109]])

In [19]:
b[0:2,0:2]=14;b

array([[ 14,  14, 104, 105],
       [ 14,  14, 108, 109]])

In [20]:
b[0:2,0:2]=[15,16];b

array([[ 15,  16, 104, 105],
       [ 15,  16, 108, 109]])

In [23]:
b[0:2,0:2]=np.arange(15,19).reshape(2,2);b

array([[ 15,  16, 104, 105],
       [ 17,  18, 108, 109]])

Fancy indexing: 1차원

In [34]:
d=np.arange(0,10);d 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
d[[1,3,5]] #fancy indexing은 차원 유지

array([1, 3, 5])

In [36]:
d[[-1,-3,-5]]+=10;d

array([ 0,  1,  2,  3,  4, 15,  6, 17,  8, 19])

In [37]:
d[range(1,10,2)]*=2;d

array([ 0,  2,  2,  6,  4, 30,  6, 34,  8, 38])

Fancy indexing : 2차원

In [38]:
a=np.arange(0,16).reshape(4,4);a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [39]:
a[[3,0,1]] #fancy indexing은 차원 유지

array([[12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

In [40]:
a[[-3,-3]]

array([[4, 5, 6, 7],
       [4, 5, 6, 7]])

In [42]:
a[[3,0,1],2] #Fancy indexing이 indexing 이랑 같이 쓸때 유지

array([14,  2,  6])

In [43]:
a[[3,0,1],[0,1,2]]

array([12,  1,  6])

In [44]:
a[np.arange(4),1:2] #np.arange 은 슬라이싱이랑 똑같음. 

array([[ 1],
       [ 5],
       [ 9],
       [13]])

In [45]:
a[np.arange(4),1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [46]:
a[np.arange(4),1:6]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [48]:
a[np.arange(4),np.arange(1)] #

array([ 0,  4,  8, 12])

In [49]:
a[np.arange(4),np.arange(4)] #0행 0열, 1행 1열, 2행 2열, 3행 3열꺼 가져옴 

array([ 0,  5, 10, 15])

In [50]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [51]:
a[[0,1,2,3][1:2]] #안에 있는 리스트를 슬라이싱 하고 인덱싱해주는거

array([[4, 5, 6, 7]])

In [52]:
a[[0,1,2,3][1:3]]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
a[[0,1,2,3][1]]

array([4, 5, 6, 7])

조건 검색

In [55]:
names=np.array([["Bob",'Joe','Will'],
                ['Will','Bob','Joe']])
names

array([['Bob', 'Joe', 'Will'],
       ['Will', 'Bob', 'Joe']], dtype='<U4')

In [56]:
names=="Bob" #조건 검색

array([[ True, False, False],
       [False,  True, False]])

In [57]:
names[names=='Bob']

array(['Bob', 'Bob'], dtype='<U4')

In [58]:
names[names!='Bob']

array(['Joe', 'Will', 'Will', 'Joe'], dtype='<U4')

In [59]:
names[~(names=='Bob')]

array(['Joe', 'Will', 'Will', 'Joe'], dtype='<U4')

In [60]:
names[names=='Bob']='Jane'
names

array([['Jane', 'Joe', 'Will'],
       ['Will', 'Jane', 'Joe']], dtype='<U4')

연습문제 1: 네모칸의 코드

In [61]:
a=np.arange(1,21).reshape(4,5);a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [62]:
a[::2,::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

연습문제 2

In [64]:
a[a%2==1]=100;a

array([[100,   2, 100,   4, 100],
       [  6, 100,   8, 100,  10],
       [100,  12, 100,  14, 100],
       [ 16, 100,  18, 100,  20]])

Python : 변경 가능 객체

In [65]:
a=np.arange(7)
b=a
c=a[1:]

In [66]:
a

array([0, 1, 2, 3, 4, 5, 6])

In [67]:
b

array([0, 1, 2, 3, 4, 5, 6])

In [68]:
c

array([1, 2, 3, 4, 5, 6])

In [69]:
a[1:3]=10

In [70]:
a

array([ 0, 10, 10,  3,  4,  5,  6])

In [71]:
b

array([ 0, 10, 10,  3,  4,  5,  6])

In [72]:
c

array([10, 10,  3,  4,  5,  6])

In [73]:
a=np.arange(7)
b=a[[3,2,1]]
c=a.copy()

In [74]:
a

array([0, 1, 2, 3, 4, 5, 6])

In [75]:
b

array([3, 2, 1])

In [76]:
c

array([0, 1, 2, 3, 4, 5, 6])

In [77]:
a[1:6]=10

In [78]:
a

array([ 0, 10, 10, 10, 10, 10,  6])

In [79]:
b

array([3, 2, 1])

In [80]:
c

array([0, 1, 2, 3, 4, 5, 6])

행과 열 변환 : 전치 Tranpose

In [82]:
a=np.arange(32).reshape(8,4);a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [83]:
a.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [84]:
a.T.T

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

Where

In [85]:
x=np.array([1.1,1.2,1.3,1.4])
y=np.array([2.1,2.2,2.3,2.4])
cond=np.array([True, True, False, False])
np.where(cond, x, y)

array([1.1, 1.2, 2.3, 2.4])

In [86]:
a=np.arange(16).reshape(4,4)
np.where(a>7,np.nan,a)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan]])