import 모듈명


In [4]:
import numpy
a=[6, 7.5, 8, 0, 1]

In [5]:
numpy.array(a)

array([6. , 7.5, 8. , 0. , 1. ])

import 모듈명 as 약자 

In [9]:
import numpy as np
a = [6, 7.5 , 8 , 0, 1]
np.array(a) #제일 많이 쓰는 표현 

array([6. , 7.5, 8. , 0. , 1. ])

리스트 vs ndarray

In [10]:
a = [6, 7.5, 8, 0, 1]
b= np.array(a)

In [11]:
b

array([6. , 7.5, 8. , 0. , 1. ])

In [12]:
a

[6, 7.5, 8, 0, 1]

In [13]:
type(a)

list

In [14]:
type(b)

numpy.ndarray

In [15]:
list(b)

[6.0, 7.5, 8.0, 0.0, 1.0]

In [17]:
b+2

array([ 8. ,  9.5, 10. ,  2. ,  3. ])

In [19]:
a+a

[6, 7.5, 8, 0, 1, 6, 7.5, 8, 0, 1]

In [20]:
b*2

array([12., 15., 16.,  0.,  2.])

ndarray 입력

In [21]:
import numpy as np
a = [[1,2,3,4],[5,6,7,8]]
b=np.array(a)
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
np.array([[1,2,3,4],[5,6,7,8]]) # ndarray는 tuple list 둘다 상관없음

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
np.array([(1,2,3,4),(5,6,7,8)])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
np.array(([1,2,3,4],[5,6,7,8]))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
np.array(((1,2,3,4),(5,6,7,8)))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

ndarray 와 데이터 구조, 차원

In [26]:
a = 'abcd'
b=list(a)
c=tuple(a)
d=dict((("a",1),("b",2)))
e=set(a)

In [33]:
np.array(a) #문자열 불가능

array('abcd', dtype='<U4')

In [34]:
np.array(b) #리스트 가능

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [35]:
np.array(c) #튜플 가능

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [36]:
np.array(d) #사전형식 불가능

array({'a': 1, 'b': 2}, dtype=object)

In [37]:
np.array(e) #set 불가능

array({'d', 'a', 'b', 'c'}, dtype=object)

size. shape

In [38]:
np.array(a).size

1

In [39]:
np.array(b).size

4

In [40]:
np.array(c).size

4

In [41]:
np.array(d).size

1

In [42]:
np.array(e).size

1

In [43]:
np.array(a).shape

()

In [44]:
np.array(b).shape

(4,)

In [45]:
np.array(c).shape

(4,)

In [46]:
np.array(d).shape

()

In [47]:
np.array(e).shape

()

In [48]:
np.array([d,e])

array([{'a': 1, 'b': 2}, {'d', 'a', 'b', 'c'}], dtype=object)

In [51]:
np.array([d,e]).size

2

In [52]:
np.array([d,e]).shape

(2,)

In [53]:
f=np.array(b)
f

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [56]:
f.shape=(2,2)
f

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [57]:
f.size

4

In [59]:
f.shape=(1,4)
f

array([['a', 'b', 'c', 'd']], dtype='<U1')

In [60]:
f.size

4

ndarray 연산

In [61]:
a=np.array([6, 7.5, 8, 1])
a

array([6. , 7.5, 8. , 1. ])

In [63]:
a+2

array([ 8. ,  9.5, 10. ,  3. ])

In [65]:
a+a

array([12., 15., 16.,  2.])

In [66]:
a*list(a)

array([36.  , 56.25, 64.  ,  1.  ])

In [67]:
a.shape=(2,2)
a

array([[6. , 7.5],
       [8. , 1. ]])

In [68]:
a+a

array([[12., 15.],
       [16.,  2.]])

ndarray 입력과 차원

In [71]:
import numpy as np
a=[[1,2,3,4],[5,6,7,8]]
b=np.array(a)
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [72]:
b.size

8

In [73]:
b.shape

(2, 4)

In [77]:
b.shape=(2,2,2)
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

dtype

In [79]:
a=np.array(['a','b','c'])
b=np.array([1,2,3])
c=np.array([1,2.,3])

In [80]:
a.dtype

dtype('<U1')

In [81]:
b.dtype

dtype('int32')

In [82]:
c.dtype

dtype('float64')

In [84]:
np.array([b,b]).dtype # 실수 < 정수 < 문자열 

dtype('int32')

In [85]:
np.array([b,c]).dtype

dtype('float64')

In [86]:
np.array([a,b]).dtype

dtype('<U11')

In [87]:
np.array([1,2,3],dtype='float').dtype

dtype('float64')

In [88]:
np.array([1,2.,3],dtype='int').dtype

dtype('int32')

In [89]:
np.array([1,2.,3],dtype='str').dtype

dtype('<U3')

In [90]:
b.astype("str")

array(['1', '2', '3'], dtype='<U11')

In [91]:
b.astype("float")

array([1., 2., 3.])

연습문제 1

In [93]:
a=list(range(1,9))
b=list(10*np.array(a))
b

[10, 20, 30, 40, 50, 60, 70, 80]

In [94]:
c=np.array(b).astype('float')
c

array([10., 20., 30., 40., 50., 60., 70., 80.])

In [95]:
c.shape=(2,4)
c

array([[10., 20., 30., 40.],
       [50., 60., 70., 80.]])