# numpy.random

In [2]:
import numpy as np
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.random.shuffle(x)
x

array([9, 7, 0, 8, 4, 3, 6, 1, 5, 2])

In [6]:
np.random.choice(x)

9

In [11]:
np.random.shuffle(x)
np.random.choice(x)

9

# numpy.random.rand

In [13]:
y=np.random.rand() # [0,1) unifomr distribution
y

0.038970502940480434

In [15]:
y=np.random.rand(7)
y

array([0.34615317, 0.61662909, 0.16309462, 0.4756453 , 0.66775109,
       0.12658843, 0.41681653])

In [17]:
y=np.random.rand(2,7)
y

array([[0.71077703, 0.67855835, 0.66328293, 0.63426091, 0.62497487,
        0.68967151, 0.94242236],
       [0.82242999, 0.37265174, 0.71960017, 0.62085659, 0.06247249,
        0.60544521, 0.9424058 ]])

In [18]:
y=np.random.rand(3,2,7)
y

array([[[0.77884703, 0.17193413, 0.13472265, 0.7862885 , 0.06121294,
         0.37333808, 0.28006898],
        [0.3701923 , 0.93483919, 0.96769512, 0.30566548, 0.65794307,
         0.61470316, 0.73416017]],

       [[0.42158217, 0.88196713, 0.63486439, 0.53043189, 0.33002847,
         0.36974395, 0.86103127],
        [0.34281779, 0.67376266, 0.74236444, 0.91093718, 0.46702975,
         0.95126278, 0.05209224]],

       [[0.88489275, 0.84350772, 0.73107917, 0.46479594, 0.00702106,
         0.56768279, 0.47801379],
        [0.60460815, 0.9582333 , 0.31894909, 0.70867188, 0.67811171,
         0.08119396, 0.8013369 ]]])

# numpy.random.randn

In [24]:
y=np.random.randn() # mean=0, variance=1, Gaussian Normal distribution 
y

-2.326529871556696

In [25]:
y=np.random.randn(7)
y

array([-1.40284647,  0.57390171, -0.40096182, -0.26840135, -0.34907653,
        1.18426358, -1.1237119 ])

In [26]:
y=np.random.randn(2,7)
y

array([[ 0.72334851, -0.33881267, -0.47991909,  0.73194613,  1.96563014,
         0.11655957,  0.65401184],
       [-0.95580522, -1.25334105, -0.39914985,  0.62457092, -2.53688862,
         0.46734881, -1.90582991]])

In [27]:
y=np.random.randn(3,2,7)
y

array([[[-1.19730013,  0.25374011,  0.14728096, -1.05397638,
          0.21268714, -1.21782882, -0.68508048],
        [ 0.48055239, -1.31779581, -0.98243403,  1.51667424,
         -0.34893321,  0.46499853,  1.0435466 ]],

       [[ 1.52031353,  0.89504908,  0.77714813, -0.00858624,
         -3.49251306,  0.05666705,  0.90772099],
        [ 1.06837944, -0.11039126, -0.43854272,  1.22938317,
         -0.80336273,  0.16185954, -0.13109895]],

       [[ 1.96532129, -0.51427013,  1.01102211, -0.04480484,
         -1.15231562,  0.63055676, -0.2182198 ],
        [-0.66981393, -0.16576089,  0.26979957,  0.44862894,
         -0.06185717, -0.272174  ,  0.29274655]]])

# numpy.cumsum

In [29]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [31]:
np.cumsum(a,dtype=float)

array([ 1.,  3.,  6., 10., 15., 21.])

In [33]:
np.cumsum(a,axis=0)

array([[1, 2, 3],
       [5, 7, 9]], dtype=int32)

In [34]:
np.cumsum(a,axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15]], dtype=int32)

In [37]:
a=np.array([[1,2,3],
            [4,5,6]])
a0=a[:,0]
a

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
a1=a[:,2]
a1

array([3, 6])

In [41]:
ar0=a[0,:]
ar0

array([1, 2, 3])

In [42]:
ar1=a[1,:]
ar1

array([4, 5, 6])

# reshape()

In [45]:
arr=np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [46]:
arr.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [47]:
arr.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [48]:
arr=np.arange(15)
arr.reshape((5,-1)) #-1은 5행을 먼저 맞춰주고 이 행렬을 맞추기 위해서 3으로 바뀜 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

# ravel() : return a contiguous flattened array

In [51]:
arr=np.arange(15).reshape(5,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [52]:
arr.ravel() #axis =0 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [54]:
arr.ravel('F') #axis =1

array([ 0,  3,  6,  9, 12,  1,  4,  7, 10, 13,  2,  5,  8, 11, 14])

In [55]:
arr=np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [56]:
np.ravel(arr,order='F')

array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14])

In [57]:
np.ravel(arr)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [58]:
np.ravel(arr,order='C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# concatenate() 배열 붙이기 

In [60]:
a1=np.array([[1,2,3],[4,5,6]])
a2=np.array([[7,8,9],[10,11,12]])
np.concatenate([a1,a2],axis=0) # 밑에다가 붙이는거

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [61]:
np.concatenate([a1,a2],axis=1) #옆에다가 붙이는거 

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

# repeat()

In [63]:
arr=np.arange(3)
arr


array([0, 1, 2])

In [64]:
arr.repeat(4)

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2])

In [65]:
arr.repeat([2,3,4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [4]:
arr=np.random.randn(2,2)
arr

array([[0.00171113, 0.80937986],
       [1.54213225, 0.61581632]])

In [5]:
arr.repeat([2,3],axis=0)

array([[0.00171113, 0.80937986],
       [0.00171113, 0.80937986],
       [1.54213225, 0.61581632],
       [1.54213225, 0.61581632],
       [1.54213225, 0.61581632]])

In [6]:
arr.repeat([2,3],axis=1)

array([[0.00171113, 0.00171113, 0.80937986, 0.80937986, 0.80937986],
       [1.54213225, 1.54213225, 0.61581632, 0.61581632, 0.61581632]])

# tile() 똑같은거 붙여줌 

In [8]:
arr

array([[0.00171113, 0.80937986],
       [1.54213225, 0.61581632]])

In [9]:
np.tile(arr,2)

array([[0.00171113, 0.80937986, 0.00171113, 0.80937986],
       [1.54213225, 0.61581632, 1.54213225, 0.61581632]])

In [10]:
np.tile(arr,(2,1))

array([[0.00171113, 0.80937986],
       [1.54213225, 0.61581632],
       [0.00171113, 0.80937986],
       [1.54213225, 0.61581632]])

In [11]:
np.tile(arr,(3,2))

array([[0.00171113, 0.80937986, 0.00171113, 0.80937986],
       [1.54213225, 0.61581632, 1.54213225, 0.61581632],
       [0.00171113, 0.80937986, 0.00171113, 0.80937986],
       [1.54213225, 0.61581632, 1.54213225, 0.61581632],
       [0.00171113, 0.80937986, 0.00171113, 0.80937986],
       [1.54213225, 0.61581632, 1.54213225, 0.61581632]])

# range와 numpy.arange 비교

In [13]:
pyL=range(1,10)
print(type(pyL),pyL)

<class 'range'> range(1, 10)


In [14]:
npA=np.arange(1,10,dtype=np.float)
print(type(npA),npA)

<class 'numpy.ndarray'> [1. 2. 3. 4. 5. 6. 7. 8. 9.]


C:\Users\user\AppData\Local\Temp/ipykernel_19784/1270515223.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  npA=np.arange(1,10,dtype=np.float)


In [15]:
npA=np.arange(1,10,dtype=np.int)
print(type(npA),npA)

<class 'numpy.ndarray'> [1 2 3 4 5 6 7 8 9]


C:\Users\user\AppData\Local\Temp/ipykernel_19784/2441809604.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  npA=np.arange(1,10,dtype=np.int)


In [16]:
# 연산방식: 섭씨와 화씨 온도 변환

In [17]:
cvalues=[25.3, 24.8, 26.9, 23.9]
c=np.array(cvalues)
print(c)
F=c*9/5+32
print(type(F),F)

[25.3 24.8 26.9 23.9]
<class 'numpy.ndarray'> [77.54 76.64 80.42 75.02]
